name: ec2 deploy
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-lastest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: ssh to ec2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrects.SHH_PRIVATE_KEY }}
          host: ${{ secrects.HOST }}
          username: ${{ secrects.USER }}
          script: |
            cd streamlit_car_price_app
            git pull










